### PR TITLE
content sort and update in Job Board

### PR DESCRIPTION
**Pull request by jethoof**
Named it Jethoof's Emporium of Requests, added Tips on Creating Creatures for Encounters.

### CODE REVIEW

**Comment by sigrunixia** [comment]
@Craftidore What do you want to do regarding changes to the .obsidian folder?

**Comment by Craftidore** [comment]
I'll disregard them in this specific case. I'll have a better answer once I have a contribution guidelines note setup, but the general policy is no changing .obsidian settings without a good reason, and it should be it's own commit & PR. The guide will also instruct people to copy the existing `.obsidian` folder into one named after their username, and add that to the .gitignore, so one can have their own settings (you'll notice I have `.ctaftidore/` in the .gitignore). However, you'd still need to make sure everything works with the main `.obsidian` config

**Comment by jethoof** [comment]
Is there something I need to set up on my end to do something about that?

**Comment by sigrunixia** [comment]
> Is there something I need to set up on my end to do something about that?

You can create a `.gitignore` file [that can automatically ignore](https://stackoverflow.com/questions/10744305/how-to-create-a-gitignore-file) the .obsidian folder. This is something Craftidore would establish at some point in the main repo, but in the interim it keeps you fork from uploading it.

**Comment by Craftidore** [comment]
@sigrunixia it's not actually enough to gitignore the`.obsidian` folder, as a bunch of the files there are already tracked, which overrides the gitignore. Hence why people would need a separate config folder to gitignore.

**Pull request merged**
